const carBrands = [
   { word: "Alfa Romeo", category: "Marcas de vehiculos" },
   { word: "Alldays & Onions", category: "Marcas de vehiculos" },
   { word: "Alvis", category: "Marcas de vehiculos" },
   { word: "Arab (automóvil)", category: "Marcas de vehiculos" },
   { word: "Audi", category: "Marcas de vehiculos" },
   { word: "Austin Motor Company", category: "Marcas de vehiculos" },
   { word: "Automobiles Talbot France", category: "Marcas de vehiculos" },
   { word: "Automóviles de Ecuador", category: "Marcas de vehiculos" },
   { word: "Bentley Motors Limited", category: "Marcas de vehiculos" },
   { word: "Birmingham Small Arms Company", category: "Marcas de vehiculos" },
   { word: "BMW M", category: "Marcas de vehiculos" },
   { word: "BSA (automóviles)", category: "Marcas de vehiculos" },
   { word: "Cadillac", category: "Marcas de vehiculos" },
   { word: "Carbodies", category: "Marcas de vehiculos" },
   { word: "Citroën", category: "Marcas de vehiculos" },
   { word: "Clément-Talbot", category: "Marcas de vehiculos" },
   { word: "Darracq Inglaterra", category: "Marcas de vehiculos" },
   { word: "Darracq Motor", category: "Marcas de vehiculos" },
   { word: "DeLorean Motor Company", category: "Marcas de vehiculos" },
   { word: "Dodge", category: "Marcas de vehiculos" },
   { word: "Ferrari", category: "Marcas de vehiculos" },
   { word: "Fiat Chrysler Automobiles", category: "Marcas de vehiculos" },
   { word: "General Motors OBB", category: "Marcas de vehiculos" },
   { word: "Georges Irat", category: "Marcas de vehiculos" },
   { word: "GMC (automóviles)", category: "Marcas de vehiculos" },
   { word: "Grupo Volkswagen", category: "Marcas de vehiculos" },
   { word: "Human Horizons", category: "Marcas de vehiculos" },
   { word: "Covini C6W", category: "Marcas de vehiculos" },
   { word: "Jensen Motors", category: "Marcas de vehiculos" },
   { word: "Jowett Cars", category: "Marcas de vehiculos" },
   { word: "Koenigsegg", category: "Marcas de vehiculos" },
   { word: "Lamborghini", category: "Marcas de vehiculos" },
   { word: "Lanchester Motor Company", category: "Marcas de vehiculos" },
   { word: "Lea-Francis", category: "Marcas de vehiculos" },
   { word: "Lexus", category: "Marcas de vehiculos" },
   { word: "Lincoln Motor Company", category: "Marcas de vehiculos" },
   { word: "Lister Motor Company", category: "Marcas de vehiculos" },
   { word: "Lotus Cars", category: "Marcas de vehiculos" },
   { word: "Lynk & Co", category: "Marcas de vehiculos" },
   { word: "Mazda", category: "Marcas de vehiculos" },
   { word: "McLaren Automotive", category: "Marcas de vehiculos" },
   { word: "McLaren Group", category: "Marcas de vehiculos" },
   { word: "Mercedes Benz", category: "Marcas de vehiculos" },
   { word: "Mitsubishi", category: "Marcas de vehiculos" },
   { word: "Moteur Development International", category: "Marcas de vehiculos" },
   { word: "Muntz Car Company", category: "Marcas de vehiculos" },
   { word: "Nissan", category: "Marcas de vehiculos" },
   { word: "Pagani", category: "Marcas de vehiculos" },
   { word: "Peugeot", category: "Marcas de vehiculos" },
   { word: "Phoenix (automóviles)", category: "Marcas de vehiculos" },
   { word: "Piëch Automotive", category: "Marcas de vehiculos" },
   { word: "Pontiac", category: "Marcas de vehiculos" },
   { word: "Porsche", category: "Marcas de vehiculos" },
   { word: "Railton (automóvil)", category: "Marcas de vehiculos" },
   { word: "Renault", category: "Marcas de vehiculos" },
   { word: "Renault do Brasil", category: "Marcas de vehiculos" },
   { word: "Renault Rusia", category: "Marcas de vehiculos" },
   { word: "Revoz", category: "Marcas de vehiculos" },
   { word: "Ruf Automobile", category: "Marcas de vehiculos" },
   { word: "Saleen", category: "Marcas de vehiculos" },
   { word: "Shelby SuperCars", category: "Marcas de vehiculos" },
   { word: "Sociedad de Maestranzas y Galvanización", category: "Marcas de vehiculos" },
   { word: "Standard Motor Company", category: "Marcas de vehiculos" },
   { word: "Stellantis", category: "Marcas de vehiculos" },
   { word: "Subaru", category: "Marcas de vehiculos" },
   { word: "Sunbeam-Talbot", category: "Marcas de vehiculos" },
   { word: "Suzuki", category: "Marcas de vehiculos" },
   { word: "Toyota", category: "Marcas de vehiculos" },
   { word: "Triumph Motor Company", category: "Marcas de vehiculos" },
   { word: "VAM", category: "Marcas de vehiculos" },
   { word: "VIA Motors", category: "Marcas de vehiculos" },
   { word: "Volkswagen", category: "Marcas de vehiculos" },
   { word: "Wolseley Motors", category: "Marcas de vehiculos" },
];
